# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes






# Serving
detach              : false
baseurl             : "DrinkUp" # does not include hostname
show_dir_listing    : false


